### PR TITLE
add breadcrumb

### PR DESCRIPTION
**Pull request by duythien**
For #7

### CODE REVIEW

**Comment by and1truong** [comment]
I don't think this PR works. 

I expect breadcrumb: "Home > Jobs".
Your PR do: "Home > %page_title"

So I think we just need enable https://www.drupal.org/project/custom_breadcrumbs, config, export the configuration.

Thank you (:

**Comment by duythien** [comment]
@andytruong  checking here http://drupalvietnam.thien.go1.com.vn/viec-lam/tuyen-dung-lap-trinh-vien-drupal

**Comment by and1truong** [comment]
Look good… but can we use custom_breadcrumbs module please?

**Comment by duythien** [comment]
Yes, If your website have module this , I think  issues is close

**Pull request closed without merging**
